### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by sekarpdkt** [gabomdq/pytgvoip#1]
hi

While executing `make` command was getting error related with aclocal. Manually edited Makefile and changed reference to specific version of 1.16 for aclocal and automake. Then it got compiled successfully. However when I execute this command getting this error

```
$pythpython3 tgcall.py api_id='apiId' api_hash='apiHash' phone='mynumber' user_id=tocalleduserID dbkey='dbKey'
Traceback (most recent call last):
  File "tgcall.py", line 11, in <module>
    from tgvoip import call
ImportError: libtgvoip.so.0: cannot open shared object file: No such file or directory
$ ls -tla /usr/local/lib/libtgvoip.so.0
lrwxrwxrwx 1 root root 18 Dec 25 18:12 /usr/local/lib/libtgvoip.so.0 -> libtgvoip.so.0.0.0
sekar@UDOO-x86:/ssd/bot/telegram/pytgvoip$ 
on3 tgcall.py api_id .....................
Traceback (most recent call last):
  File "tgcall.py", line 11, in <module>
    from tgvoip import call
ImportError: libtgvoip.so.0: cannot open shared object file: No such file or directory
$ ls -tla /usr/local/lib/libtgvoip.so.0
lrwxrwxrwx 1 root root 18 Dec 25 18:12 /usr/local/lib/libtgvoip.so.0 -> libtgvoip.so.0.0.0
$ ls -tla /usr/local/lib/libtgvoip*
-rw-r--r-- 1 root root 14839458 Dec 25 18:12 /usr/local/lib/libtgvoip.a
-rwxr-xr-x 1 root root      961 Dec 25 18:12 /usr/local/lib/libtgvoip.la
lrwxrwxrwx 1 root root       18 Dec 25 18:12 /usr/local/lib/libtgvoip.so -> libtgvoip.so.0.0.0
lrwxrwxrwx 1 root root       18 Dec 25 18:12 /usr/local/lib/libtgvoip.so.0 -> libtgvoip.so.0.0.0
-rwxr-xr-x 1 root root  6423416 Dec 25 18:12 /usr/local/lib/libtgvoip.so.0.0.0
```

Edit #1:

I added /usr/local/lib to my LD_LIBRARY_PATH by executing `export  LD_LIBRARY_PATH=/usr/local/lib`. Now getting following error

```
Traceback (most recent call last):
  File "tgcall.py", line 11, in <module>
    from tgvoip import call
ImportError: cannot import name 'call'
```

**Comment by sekarpdkt** [comment]
As latest pytgvoip is not having `call` method, need to use `_call_start` and `_call_end`. It works. `python-telegram` also needed some changes to support `updateCall` messages. Those changes might get merged shortly in `python-telegram`. If required, can share working example without need for `mqtt`.
